# -*- coding: utf-8 -*-
"""Palindrome

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BcER-3M2Kbs5oQWNEHmLrzbOtKrmgY0X
"""

def check(s):
  return str(s)==str(s)[::-1]

check(121)

check(10)

