# -*- coding: utf-8 -*-
"""Sum_to_N

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BcER-3M2Kbs5oQWNEHmLrzbOtKrmgY0X
"""

def solve(nums,target):
  if len(nums)<=0:
    return False
  d={}
  for i in range(len(nums)):
    if nums[i] in d:
      return d[nums[i]], i
    else:
      d[target-nums[i]] = i
  return False

nums = [2,7,11,15]

target = 9

print(solve(nums,target))

